services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    restart: "${RESTART_POLICY:-always}"
    deploy:
      resources:
        limits:
          cpus: "${CHROMADB_CPUS_LIMIT:-1}"
          memory: "${CHROMADB_MEMORY_LIMIT:-2G}"
    volumes:
      - chromadb_data:/chroma/data
    ports:
      - "${CHROMADB_PORT:-8000}:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/data
    networks:
      - infra_shared

volumes:
  chromadb_data:
    name: chromadb_data

networks:
