services:
  appsmith:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appsmith.rule=Host(`appsmith.localhost`)"
      - "traefik.http.routers.appsmith.entrypoints=web,websecure"
      - "traefik.http.routers.appsmith.tls=true"
      - "traefik.http.services.appsmith.loadbalancer.server.port=80"
    container_name: appsmith
    image: appsmith/appsmith-ce:v2.1
    restart: "${RESTART_POLICY:-always}"
    deploy:
      resources:
        limits:
          cpus: "${APPSMITH_CPUS_LIMIT:-2}"
          memory: "${APPSMITH_MEMORY_LIMIT:-4G}"
    volumes:
      - appsmith_data:/appsmith-stacks
    ports:
      - "${APPSMITH_PORT:-8091}:80"
      - "${APPSMITH_HTTPS_PORT:-8444}:443"
    networks:
      - infra_shared
      - dev_tools

volumes:
  appsmith_data:
    name: appsmith_data

networks:
  infra_shared:
    external: true
  dev_tools:
    external: true
