services:
  mailpit:
    container_name: dev_mailpit
    image: axllent/mailpit:latest
    restart: "${RESTART_POLICY:-always}"
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_WEB_PORT:-8025}:8025"
    networks:
      - dev_tools

networks:
  dev_tools:
    name: dev_tools
    driver: bridge
