tls:
  certificates:
    - certFile: /certs/server.crt
      keyFile: /certs/server.key

http:
  routers:
    adminer:
      rule: "Host(`adminer.localhost`)"
      service: adminer
      entryPoints:
        - web
        - websecure
      tls: {}
    
    mailpit:
      rule: "Host(`mailpit.localhost`)"
      service: mailpit
      entryPoints:
        - web
        - websecure
      tls: {}
    
    rabbitmq:
      rule: "Host(`rabbitmq.localhost`)"
      service: rabbitmq
      entryPoints:
        - web
        - websecure
      tls: {}
    
    redisinsight:
      rule: "Host(`redisinsight.localhost`)"
      service: redisinsight
      entryPoints:
        - web
        - websecure
      tls: {}
    
    gitea:
      rule: "Host(`gitea.localhost`)"
      service: gitea
      entryPoints:
        - web
        - websecure
      tls: {}
    
    jenkins:
      rule: "Host(`jenkins.localhost`)"
      service: jenkins
      entryPoints:
        - web
        - websecure
      tls: {}
    
    concourse:
      rule: "Host(`concourse.localhost`)"
      service: concourse
      entryPoints:
        - web
        - websecure
      tls: {}
    
    sonarqube:
      rule: "Host(`sonarqube.localhost`)"
      service: sonarqube
      entryPoints:
        - web
        - websecure
      tls: {}
    
    minio:
      rule: "Host(`minio.localhost`)"
      service: minio-console
      entryPoints:
        - web
        - websecure
      tls: {}

    minio-s3:
      rule: "Host(`s3.minio.localhost`)"
      service: minio-s3
      entryPoints:
        - web
        - websecure
      tls: {}

    dockge:
      rule: "Host(`dockge.localhost`)"
      service: dockge
      entryPoints:
        - web
        - websecure
      tls: {}

    portainer:
      rule: "Host(`portainer.localhost`)"
      service: portainer
      entryPoints:
        - web
        - websecure
      tls: {}

    n8n:
      rule: "Host(`n8n.localhost`)"
      service: n8n
      entryPoints:
        - web
        - websecure
      tls: {}

    grafana:
      rule: "Host(`grafana.localhost`)"
      service: grafana
      entryPoints:
        - web
        - websecure
      tls: {}

  services:
    adminer:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"

    mailpit:
      loadBalancer:
        servers:
          - url: "http://mailpit:8025"

    rabbitmq:
      loadBalancer:
        servers:
          - url: "http://rabbitmq:15672"

    redisinsight:
      loadBalancer:
        servers:
          - url: "http://redisinsight:5540"

    gitea:
      loadBalancer:
        servers:
          - url: "http://gitea:3000"

    jenkins:
      loadBalancer:
        servers:
          - url: "http://jenkins:8080"

    concourse:
      loadBalancer:
        servers:
          - url: "http://concourse:8080"

    sonarqube:
      loadBalancer:
        servers:
          - url: "http://sonarqube:9000"

    minio-console:
      loadBalancer:
        servers:
          - url: "http://minio:9001"

    minio-s3:
      loadBalancer:
        servers:
          - url: "http://minio:9000"

    dockge:
      loadBalancer:
        servers:
          - url: "http://dockge:5001"

    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
