services:
  traefik:
    image: "traefik:v2.10.7"
    container_name: "traefik"
    deploy:
      resources:
        limits:
          cpus: "${TRAEFIK_CPUS_LIMIT:-1}"
          memory: "${TRAEFIK_MEMORY_LIMIT:-512M}"
        reservations:
          cpus: "${TRAEFIK_CPUS_RESERVED:-0.5}"
          memory: "${TRAEFIK_MEMORY_RESERVED:-256M}"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file=true"
      - "--providers.file.filename=/traefik/config.yml"
      - "--log.level=${LOG_LEVEL:-INFO}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/home/thangtt/Documents/GitHub/docker-shared-services/traefik/config.yml:/traefik/config.yml:ro"
      - "/home/thangtt/Documents/GitHub/docker-shared-services/traefik/certs:/certs:ro"
    restart: "${RESTART_POLICY:-always}"
    networks:
      - dev_tools

networks:
  dev_tools:
    name: dev_tools
    external: true
