services:
  traefik:
    image: "traefik:v2.11.31"
    container_name: "traefik"
    deploy:
      resources:
        limits:
          cpus: "${TRAEFIK_CPUS_LIMIT:-1}"
          memory: "${TRAEFIK_MEMORY_LIMIT:-512M}"
        reservations:
          cpus: "${TRAEFIK_CPUS_RESERVED:-0.5}"
          memory: "${TRAEFIK_MEMORY_RESERVED:-256M}"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file=true"
      - "--providers.file.filename=/traefik/config.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=infra_shared"
      - "--log.level=${LOG_LEVEL:-INFO}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config.yml:/traefik/config.yml:ro
      - ./traefik/certs:/certs:ro
    restart: "${RESTART_POLICY:-always}"
    networks:
      infra_shared:
        aliases:
          - minio.localhost
          - s3.minio.localhost

networks:
