services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.13-management-alpine"
    restart: "${RESTART_POLICY:-always}"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD:-guest}"
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    networks:
      - dev_tools
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev_tools:
    name: dev_tools
    external: true

volumes:
  rabbitmq_data:
