services:
  mysql8:
    container_name: mysql8
    image: "mysql:8.4.6"
    restart: "${RESTART_POLICY:-always}"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: "${MYSQL_CPUS_LIMIT:-1}"
          memory: "${MYSQL_MEMORY_LIMIT:-1G}"
        reservations:
          cpus: "${MYSQL_CPUS_RESERVED:-0.5}"
          memory: "${MYSQL_MEMORY_RESERVED:-512M}"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE:-cloud}"
      MYSQL_USER: "${MYSQL_USER:-uid}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password102}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-password102}"
      TZ: "${TZ:-Asia/Ho_Chi_Minh}"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - infra_shared
      - dev_tools
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  infra_shared:
    external: true
  dev_tools:
    external: true

volumes:
  mysql_data:
