services:
  adminer:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=web,websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    container_name: adminer
    image: adminer:5.4.1
    restart: "${RESTART_POLICY:-always}"
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    networks:
      - infra_shared
      - dev_tools
    volumes:
      - ./adminer.css:/var/www/html/adminer.css:ro

networks:
  infra_shared:
    external: true
  dev_tools:
    external: true
