services:
  adminer:
    container_name: adminer
    image: adminer:5.4.1
    restart: "${RESTART_POLICY:-always}"
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    networks:
      - dev_tools
    volumes:
      - ./adminer.css:/var/www/html/adminer.css:ro
    depends_on:
      postgres:
        condition: service_healthy
      mysql8:
        condition: service_healthy

networks:
  dev_tools:
    name: dev_tools
    external: true
