services:
  jenkins:
    image: tranthethang/jenkins:latest
    container_name: dev_jenkins
    restart: "${RESTART_POLICY:-always}"
    ports:
      - "${JENKINS_PORT:-8090}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev_tools
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - TZ="${TZ:-Asia/Ho_Chi_Minh}"
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - JENKINS_DB_NAME=${JENKINS_DB_NAME:-jenkins}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password102}

networks:
  dev_tools:
    name: dev_tools
    driver: bridge

volumes:
  jenkins_home:
