services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.0
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    environment:
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    deploy:
      resources:
        limits:
          cpus: ${OTEL_COLLECTOR_CPU_LIMIT:-0.1}
          memory: ${OTEL_COLLECTOR_MEM_LIMIT:-128M}
    ports:
      - "${OTEL_COLLECTOR_PORT_GRPC:-4317}:4317" # OTLP gRPC
      - "${OTEL_COLLECTOR_PORT_HTTP:-4318}:4318" # OTLP HTTP
    networks:
      - infra_shared
      - dev_tools

  jaeger:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.localhost`)"
      - "traefik.http.routers.jaeger.entrypoints=web,websecure"
      - "traefik.http.routers.jaeger.tls=true"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
    image: jaegertracing/all-in-one:1.76.0
    container_name: jaeger
    environment:
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
    deploy:
      resources:
        limits:
          cpus: ${JAEGER_CPU_LIMIT:-0.2}
          memory: ${JAEGER_MEM_LIMIT:-512M}
    ports:
      - "${JAEGER_PORT:-16686}:16686" # Web UI
    networks:
      - infra_shared
      - dev_tools

  prometheus:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web,websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    environment:
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: ${PROMETHEUS_CPU_LIMIT:-0.1}
          memory: ${PROMETHEUS_MEM_LIMIT:-256M}
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - infra_shared
      - dev_tools

networks:
  infra_shared:
    external: true
  dev_tools:
    external: true
