services:
  redisinsight:
    container_name: dev_redisinsight
    image: "redis/redisinsight:latest"
    restart: "${RESTART_POLICY:-always}"
    ports:
      - "${REDISINSIGHT_PORT:-5540}:5540"
    networks:
      - dev_tools
    volumes:
      - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy

networks:
  dev_tools:
    name: dev_tools
    driver: bridge

volumes:
  redisinsight_data:
