services:
  redisinsight:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redisinsight.rule=Host(`redisinsight.localhost`)"
      - "traefik.http.routers.redisinsight.entrypoints=web,websecure"
      - "traefik.http.routers.redisinsight.tls=true"
      - "traefik.http.services.redisinsight.loadbalancer.server.port=5540"
    container_name: redisinsight
    image: "redis/redisinsight:2.70.1"
    restart: "${RESTART_POLICY:-always}"
    deploy:
      resources:
        limits:
          cpus: "${REDISINSIGHT_CPUS_LIMIT:-0.5}"
          memory: "${REDISINSIGHT_MEMORY_LIMIT:-512M}"
        reservations:
          cpus: "${REDISINSIGHT_CPUS_RESERVED:-0.25}"
          memory: "${REDISINSIGHT_MEMORY_RESERVED:-256M}"
    ports:
      - "${REDISINSIGHT_PORT:-5540}:5540"
    networks:
      - infra_shared
      - dev_tools
    volumes:
      - redisinsight_data:/data

networks:
  infra_shared:
    external: true
  dev_tools:
    external: true

volumes:
  redisinsight_data:
