services:
  redisinsight:
    container_name: dev_redisinsight
    image: "redis/redisinsight:1.15.0"
    restart: "${RESTART_POLICY:-always}"
    deploy:
      resources:
        limits:
          cpus: "${REDISINSIGHT_CPUS_LIMIT:-0.5}"
          memory: "${REDISINSIGHT_MEMORY_LIMIT:-512M}"
        reservations:
          cpus: "${REDISINSIGHT_CPUS_RESERVED:-0.25}"
          memory: "${REDISINSIGHT_MEMORY_RESERVED:-256M}"
    ports:
      - "${REDISINSIGHT_PORT:-5540}:5540"
    networks:
      - dev_tools
    volumes:
      - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy

networks:
  dev_tools:
    name: dev_tools
    driver: bridge

volumes:
  redisinsight_data:
